### ISSUE TITLE
Knuckles driver not public

### ISSUE THREAD

**Issue by seiferth** [spayne/soft_knuckles#1]
Hi,

First of all, thanks a lot for the driver, there is way too little examples for SteamVR drivers out there, so I'm sure this will help many people a lot!
Sadly, it doesn't seem like the Knuckles driver from Steam can be downloaded without pairing the real Knuckles controllers first, is there maybe a different way of getting the rendermodels?
Also, I wanted to ask if you're going to try to implement the Skeleton as well, and if so, what the approximate timeline for this is going to be? 

Thanks and have a good day!
Hagen

**Comment by spayne** [comment]
Thanks for letting me know that the driver isn't public...  Something must have changed since June 25 because I was able to purchase and download it before without owning a device (let alone pairing) by using the appid.  i.e. I went to https://help.steampowered.com/en/wizard/HelpWithGame/?appid=633750 and was able to purchase it from there.  I'm assuming this doesn't work anymore  - could you check?.  Like I said, I don't have the real knuckles.

Anyway I don't like that my project has that dependency.   The references are there as a form of scaffolding/bootstrapping so I could bring up the driver without having to make my own art assets and keeping it 'honest' in that it can cover that amount of input types.   I should replace my references to rendermodels with a similar layout.  I'll do this today.

Regarding the skeleton animation - my intention is to do this.  It'll probably be programmer art - probably just pop between on and off poses for the finger/controller bones.  I'm not sure exactly when.  Maybe later this week.  What do you think would make it most useful?

**Comment by seiferth** [comment]
So when I go to your link I get to the Support page of that driver, where it says "This product is not in your Steam Library." with a link to the store page. When I click that link however (https://store.steampowered.com/app/633750/), I'm being redirected to https://store.steampowered.com/. You could try seeing what happens if you click that link in a private browsing tab or while logged into a different steam account. Or maybe it's some sort of geoblocking (For reference, I'm in Switzerland)? 

About the skeletons, yeah, switching between two different states should be more than enough to see how it's working. Looking forward to seeing it implemented!

Cheers,
Hagen

**Comment by spayne** [comment]
I think it's now doing the same for me as for you - so I don't think it's geoblocking (I'm in the US).  I think perhaps something has changed on Valve's end that that stops that app id from being added to your list of installed games.

**Comment by spayne** [comment]
@seiferth - I replaced the references into Valve's driver with placeholder art.  It doesn't look as nice, but at least that dependency is cleaned up.  If you have a chance, let me know if you can get it working.

**Comment by seiferth** [comment]
So I tried running it today, and I got relatively far. I managed to get the R and L images to show up after the telnet thing. Then Steamvr prompted me to install the Knuckles drivers:
![knuckles driver](https://user-images.githubusercontent.com/2724494/42946950-7bff271c-8b6c-11e8-870c-dd6e321d067d.png)
However, it requires me to click Install inside VR and it won't accept clicking with a different controller (I tried m WIndows MR controller and couldn't click it). As for the soft_knuckles, I don't get any error, and can also set the position through the debug client, but somehow can't see the controllers inside VR, maybe the position is somehow in a diffrent coordinate system than ma WMR headset?

P.S.: Your bat file only works if the bin/win64 folders alread exist, so maybe you could add them, it would save the next person some time.

**Comment by spayne** [comment]
Thanks for trying it out.    It'll help make the example a better one.

I do have a windows MR controller as well - so I'll try and reproduce your observations and see if I can either document or add some better support.  It's definitely different coordinate systems - the 'pos' command is just setting the coordinates into the 'device' coordinate space (0,0,0 is one of my light houses).   It'll be interesting to see what windows MR is doing.
