### ISSUE TITLE
What would be required to have soft vive trackers?

### ISSUE THREAD

**Issue by Lhun** [spayne/soft_knuckles#2]
Hey there, thanks for making this. 
There's actually a bit of a bounty I want to put together for a universal software driver for the vive TRACKERS using off the shelf cameras so that vrchat and other applications can have full body without the purchase of vive trackers. 
There's extremely fast, accurate, and dense realtime pose estimation from commodity RGB cameras and other devices like low light and colour led available now thanks to pytorch and other RNN, but there's nothing to take a joint/foot/etc and emulate vive trackers. 
Your driver seems absolutely perfect, what would it take to pipe data from a video stream to it and make steamVR see it as a vive tracker rather than knuckles?
Software like this could then be used to pipe in data to it: 
https://github.com/CMU-Perceptual-Computing-Lab/openpose

**Comment by spayne** [comment]
My driver is a good starting point to to announce the presence of those simulated trackers and forward on tracking information, icons and state.

To get the rest of your system to work, there are some more details that need to be accounted for:

Are you wanting to have both tracking spaces running simultaneously.   I mean you want to have vive hmds and controllers working along side the simulated trackers? I'm assuming yes.

To do this you properly you are going to have to map from your new tracking space into Valve's raw tracking space.  This is because the runtime and compositor are using forward projection of raw poses and want that information.   This is requirement is described in https://github.com/ValveSoftware/openvr/wiki/TrackingOverrides

Mapping might be a one time thing or a frequent thing depending on if the RawPoseSpace and OpenPoseSpaces drift apart.  Also, how to calibrate spaces would need to be solved.

Time synchronization should also be done.

So you'd need to figure out how to calibrate spaces, how to map spaces, how to keep time synchronization .

**Comment by Lhun** [comment]
Thanks for the response! Thankfully, vrchat solves a lot of this by
requiring the user to tpose for full body tracking. The virtual trackers
would initially be aligned in depth as a value directly under and in line
with the hmd and controllers. Then, they're tracked in realtime.

**Comment by spayne** [comment]
So that's good news:  Sounds like the spatial mapping has a solution.

Does the t-pose calibration also collect some sort of timing offset?  Even if it doesn't it probably could.

**Comment by Lhun** [comment]
The t pose is specifically for lining up an avatar's armature but we could
hook that moment to align things and set the timer offset based on what was
grabbed from the previous calibration. There also appears to be GAN based
pretrained models for depth estimation from monocular rgb now too.

**Comment by Lhun** [comment]
Also, I re-read your comment, if I or the group I'm talking to do something using openpose, it actually does raw poses as a variable that is intended to be accessed in a forward way, much the same as actual hardware would be. 
https://media.discordapp.net/attachments/434880839462027275/484458949379227699/unknown.png
https://cdn.discordapp.com/attachments/434880839462027275/484459672930091019/unknown.png

**Comment by lukis101** [comment]
The VRChat calibration should be ignored in this context, Its only to get the positional and angular offsets for binding avatar skeleton.

**Comment by Lhun** [comment]
indeed, I was just thinking of using that moment to set a more accurate timing offset based on the data from openpose or similar vs live vive input. This could/perhaps should all be done in precalibration phase of course, but I was just considering the user experience and removing the need for a first and second calibration. If you used the double trigger event to align the new tracking space into Valve's raw tracking space it would cut that step out.
Perhaps just using that known pose in an "in vr" setup phase before launching a game looking for trackers is the way to go.

**Comment by spayne** [comment]
@Lhun and @lukis101  I'm following up.  From your side, have you made progress or chosen a direction you are going to follow?

I'm also working on another controller project - this one in hardware - that might also be in line with what you are doing.  Let me know if you want to chat offline: sean.d.payne@gmail.com
