### ISSUE TITLE
Controller position and orientation being automatically reset

### ISSUE THREAD

**Issue by FireHeartMaster** [spayne/soft_knuckles#4]
I finally managed to install and use the soft knuckles driver perfectly, however, I'm facing a small issue: I am updating the position and orientation of each controller inside `SoftKnucklesProvider::RunFrame()` using `vr::VRServerDriverHost()->TrackedDevicePoseUpdated(m_knuckles[0].m_id, newPose, sizeof(DriverPose_t));,` which I can visually check is happening without any problem, but I can see each controller keeps alternating between the position and orientation I just gave it and the position and orientation it starts when initialized.

I can visually see each controller constantly alternating between these two states. Would you know what may be resetting the controllers states and how to avoid it?

**Comment by spayne** [comment]
SoftKnucklesDevice has a thread that is also updating the DevicePose based on it's own m_pose variable (https://github.com/spayne/soft_knuckles/blob/06e12804b7bc83700ba3e5e312754fad32582afa/soft_knuckles_device.cpp#L270
).  

So if you are setting the position in the Provider, then I'd expect that about 1 second later that pose will  get switched back by the Device.

From a high level: Design-wise It doesn't really make sense to update the position and orientation from the Provider - since it's a per device thing, it belongs in the SoftKnucklesDevice.

I'd add a method like "SetPose" on the SoftKnucklesDevice to set the Pose.  Depending on what you are doing you should also be aware that the thread updates pretty slowly (https://github.com/spayne/soft_knuckles/blob/master/soft_knuckles_device.cpp#L305) so you may want to update faster (e.g. 15ms) if you are wanting faster updates.  

If you don't like that timeout way of updating and you want to pull TrackedDevicePoseUpdated into another update scheme, be aware that you need to call it periodically otherwise the SteamVR runtime will consider the device to be inactive and may stop displaying it.  So what I'm saying is that there is a minimum update rate that your design will need to accomodate.

**Comment by FireHeartMaster** [comment]
Thanks, man!
I realized that the device's `TrackedDevicePoseUpdated()` was setting the pose with `GetPose()`, which just returns the device's `m_pose`. So, in order to not have `TrackedDevicePoseUpdated()` reseting the current pose from inside `SoftKnucklesDevice,` I just needed to update myself the value of `m_pose` everytime I wanted to change it, so everytime `TrackedDevicePoseUpdated` is called inside `SoftKnucklesDevice`, it just gets the last pose value I updated.

I'm still thinking about changing the design of how I should really update the pose, but I'm leaving it like that by the moment, besides the speed is good enough for testing.

Thanks again
