### ISSUE TITLE
Can I make a spin off repository that's a different name?

### ISSUE THREAD

**Issue by Emnolope** [spayne/soft_knuckles#8]
I feel that the soft_knuckles title doesn't fully express what this utility can do, perhaps OPVRD? (openvr driver)

**Comment by spayne** [comment]
You can do that if you wish. I do have ideas for how I want to evolve this project so I appreciate feedback on it.

I'd say this project is really an example input driver without hardware dependencies.   At the time I initially wrote it the hardware knuckles were not available so I attempted to make a 'software' version of it based on what I thought the real hardware driver might do.

So it turns out that a key value of this example driver is that it doesn't require hardware to run.  So someone bringing up new hardware can use it as a starting point, do things in software and then introduce the hardware specific aspects over time.

So to me, a better name for the repo could be something like 'software only openvr driver'.  Or, because you like acronyms 'SOOD' :)

**Comment by Emnolope** [comment]
HAHAHAH Sodomy, that's pretty great man. But I'm thinking along of the
lines of SVRI (Steam VR Interface.) It's because a lot of people are using
OPVRIE even though it's a mess of code.
